package com.beosbank.jbdevg.brms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FeesRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("MoneyTransfert Reference")
   private java.lang.String reference;
   @org.kie.api.definition.type.Label("Sender Name")
   private java.lang.String sender;
   @org.kie.api.definition.type.Label("Receiver Name")
   private java.lang.String receiver;
   @org.kie.api.definition.type.Label("Sender Country Name")
   private java.lang.String countryFrom;
   @org.kie.api.definition.type.Label("Receiver Country Name")
   private java.lang.String countryTo;
   @org.kie.api.definition.type.Label("Transaction Date")
   private java.util.Date trxDate;

   @org.kie.api.definition.type.Label("Amount To send to the receiver")
   private double amountToSend;

   @org.kie.api.definition.type.Label("Total Fees Amount")
   private double feesAmount;

   @org.kie.api.definition.type.Label("Is fees computed")
   private boolean feesComputed;

   @org.kie.api.definition.type.Label("Request Identifier")
   private java.lang.String requestId;

   public FeesRequest()
   {
   }

   public java.lang.String getReference()
   {
      return this.reference;
   }

   public void setReference(java.lang.String reference)
   {
      this.reference = reference;
   }

   public java.lang.String getSender()
   {
      return this.sender;
   }

   public void setSender(java.lang.String sender)
   {
      this.sender = sender;
   }

   public java.lang.String getReceiver()
   {
      return this.receiver;
   }

   public void setReceiver(java.lang.String receiver)
   {
      this.receiver = receiver;
   }

   public java.lang.String getCountryFrom()
   {
      return this.countryFrom;
   }

   public void setCountryFrom(java.lang.String countryFrom)
   {
      this.countryFrom = countryFrom;
   }

   public java.lang.String getCountryTo()
   {
      return this.countryTo;
   }

   public void setCountryTo(java.lang.String countryTo)
   {
      this.countryTo = countryTo;
   }

   public java.util.Date getTrxDate()
   {
      return this.trxDate;
   }

   public void setTrxDate(java.util.Date trxDate)
   {
      this.trxDate = trxDate;
   }

   public double getAmountToSend()
   {
      return this.amountToSend;
   }

   public void setAmountToSend(double amountToSend)
   {
      this.amountToSend = amountToSend;
   }

   public double getFeesAmount()
   {
      return this.feesAmount;
   }

   public void setFeesAmount(double feesAmount)
   {
      this.feesAmount = feesAmount;
   }

   public boolean isFeesComputed()
   {
      return this.feesComputed;
   }

   public void setFeesComputed(boolean feesComputed)
   {
      this.feesComputed = feesComputed;
   }

   public java.lang.String getRequestId()
   {
      return this.requestId;
   }

   public void setRequestId(java.lang.String requestId)
   {
      this.requestId = requestId;
   }

   public FeesRequest(java.lang.String reference, java.lang.String sender,
         java.lang.String receiver, java.lang.String countryFrom,
         java.lang.String countryTo, java.util.Date trxDate,
         double amountToSend, double feesAmount, boolean feesComputed,
         java.lang.String requestId)
   {
      this.reference = reference;
      this.sender = sender;
      this.receiver = receiver;
      this.countryFrom = countryFrom;
      this.countryTo = countryTo;
      this.trxDate = trxDate;
      this.amountToSend = amountToSend;
      this.feesAmount = feesAmount;
      this.feesComputed = feesComputed;
      this.requestId = requestId;
   }

}