package com.beosbank.jbdevg.bpms;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestStatus implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    public static final int MANDATORY_FIELDS_OK=0;
    public static final int MANDATORY_FIELDS_MISSING=1;
    

    public RequestStatus() {
    }

}