version: '3'
services:
 mysql_db_africa:
       build: ./beosbank-mysqldb-africa
       ports:
        - "3406:3306"
       volumes:
        - ./beosbank-mysqldb-africa/data:/data
 posgres_db_europa:
    build: ./beosbank-pgsqldb-europa
    ports:
     - "6432:5432"
    volumes:
     - ./beosbank-pgsqldb-europa/data:/var/lib/postgresql/data
 mongo_db_emea:
    image: "mongo:3.4.4"
    ports:
      - "28001:27017"
    volumes:
     - ./beosbank-mongodb-emea/data:/data
 mongo_db_emea_feed:
   build: ./beosbank-mongodb-emea
   links:
     - mongo_db_emea
