package com.beosbank.jbdevg.brms;

/**
 * This class was automatically generated by the data modeler tool.
 */

import java.math.BigDecimal;

public class PromotionFeesItem implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Promotion Code")
   private java.lang.String promotionCode;
   @org.kie.api.definition.type.Label(value = "Transaction Reference")
   private java.lang.String trxReference;
   @org.kie.api.definition.type.Label(value = "Total Amount Granted by this promotion")
   private java.math.BigDecimal amountGranted;

   public PromotionFeesItem()
   {
   }
   
   

   public java.lang.String getPromotionCode()
   {
      return this.promotionCode;
   }

   public void setPromotionCode(java.lang.String promotionCode)
   {
      this.promotionCode = promotionCode;
   }

   public java.lang.String getTrxReference()
   {
      return this.trxReference;
   }

   public void setTrxReference(java.lang.String trxReference)
   {
      this.trxReference = trxReference;
   }

   public java.math.BigDecimal getAmountGranted()
   {
      return this.amountGranted;
   }

   public void setAmountGranted(java.math.BigDecimal amountGranted)
   {
      this.amountGranted = amountGranted;
   }

   public PromotionFeesItem(Promotion promo, MoneyTransfert transfert)
   {
       this.promotionCode= promo.getCode();
       this.trxReference = transfert.getReference();
       this.setAmountGranted(transfert.getAmountWithoutTaxes().subtract(transfert.getAmountWithDiscount()));
   }

}